FROM golang as build

WORKDIR /go/src

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN cd examples/2.0/petstore/server \
  && go build

FROM ubuntu

COPY --from=build /go/src/examples/2.0/petstore/server/server .

CMD ["./server"]